#!/bin/bash -e
echo "Warning, the terraform locks the administration of the kubernetes cluster to the"
echo "IP address that created it. If you are running this script from a different IP"
echo "you will need to terraform apply from the new IP address"

az aks get-credentials --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_KUBERNETES_CLUSTER_NAME"

kubectl get pods -A