#!/bin/bash
#
# THis creates the service account that is key to the workload identity
# The client-id is registered in Azure Active Directory.  If you have 
# multiple identities runnin in k8s, control of the service account
# details is key to preventing application 'A' accessing another 
# applications services.
kubectl apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
  namespace: default
  annotations:  
     azure.workload.identity/client-id: "$aks_workload_app1_client_id"
  labels:
     azure.workload.identity/use: "true" 
EOF
